name: pet-store-api-tests

on: push

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: pull docker container
        run: docker pull openapitools/openapi-petstore
      - name: run docker container
        run: docker run -d -e OPENAPI_BASE_PATH=/v3 --name petstore -p 80:8080 openapitools/openapi-petstore

  test:
    timeout-minutes: 360
    needs: run-docker-container
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.37.0-jammy
    steps:
      - name: wait
        run: sleep 30s
        shell: bash
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
