name: pet-store-api-tests

on: push

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Docker container
        run: |
          docker pull openapitools/openapi-petstore
          docker run -d -e OPENAPI_BASE_PATH=/v3 -p 80:8080 openapitools/openapi-petstore
