name: pet-store-api-tests

on: push

jobs:
  run-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: install dependencies
        run: npm ci
      - uses: actions/setup-node@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: pull docker image
        run: docker pull openapitools/openapi-petstore

      - name: run docker image
        run: |
          docker run -d -e OPENAPI_BASE_PATH=/v3 --name petstore -p 80:8080 openapitools/openapi-petstore

      - name: wait until app is ready
        run: sleep 30s
        shell: bash

      - name: run api tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
